# Reference: https://docs.gradle.org/current/userguide/platforms.html

[versions]

[plugins]
spotless = { id = "com.diffplug.spotless", version = "7.0.4" }
publish = { id = "com.gradle.plugin-publish", version = "1.3.1" }

[libraries]
ktfmt =  { module = "com.facebook.ktfmt:ktfmt", version = "0.53" }
pearx-kasechange = { module = "net.pearx.kasechange:kasechange", version = "1.4.1" }


kotest-bom = { module = "io.kotest:kotest-bom", version = "5.9.1" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core" }
kotest-assertions-json = { module = "io.kotest:kotest-assertions-json" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest" }
kotest-property = { module = "io.kotest:kotest-property" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5" }

mockk = { module = "io.mockk:mockk", version = "1.14.4" }
